project:
  type: website

website:
  title: "R9"
  navbar:
    left:
      - text: "R series"
        menu: 
          - text: "Episode 1"
            href: Episode1.html
          - text: "Episode 2"
            href: Episode2.html
          - text: "Episode 3"
            href: Episode3.html
          - text: "Now you see it!"
            href: xxx.html
          - text: "Introduction to QGIS"
            href: introQGIS.html
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

